# Google App Engine deployment configuration
runtime: nodejs18

# Environment variables
env_variables:
  NODE_ENV: production
  CLOUD_PROVIDER: gcp
  DATABASE_TYPE: firestore
  FIREBASE_PROJECT_ID: your-project-id
  # Add other environment variables as needed

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check configuration
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network settings
network:
  forwarded_ports:
    - 8080

# Security headers
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# Skip files during deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?\.next/cache/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?tests?/.*$
  - ^(.*/)?test/.*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.log$