# Google Cloud Build configuration for CI/CD
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Run tests
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'test:ci']
    env:
      - 'NODE_ENV=test'

  # Run security scan
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'security:scan']

  # Build application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    env:
      - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'

  # Deploy Firestore rules and indexes
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Firebase CLI
        npm install -g firebase-tools
        
        # Deploy Firestore rules and indexes
        firebase deploy --only firestore:rules,firestore:indexes --project $PROJECT_ID --token $FIREBASE_TOKEN

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# Substitutions for environment-specific deployments
substitutions:
  _ENVIRONMENT: 'production'
  _REGION: 'us-central1'

# Timeout for the entire build
timeout: '1200s'

# Available environment variables
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-service-account/versions/latest
      env: 'FIREBASE_SERVICE_ACCOUNT_KEY'
    - versionName: projects/$PROJECT_ID/secrets/jwt-secret/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/encryption-key/versions/latest
      env: 'ENCRYPTION_KEY'