// Nexus UI Components - Modern AI-Inspired Design System

// Core Nexus Components
export { NexusButton, type NexusButtonProps } from './NexusButton'
export { NexusCard, type NexusCardProps } from './NexusCard'
export { NexusInput, type NexusInputProps } from './NexusInput'
export { NexusModal, type NexusModalProps } from './NexusModal'
export { NexusChatBubble, type NexusChatBubbleProps } from './NexusChatBubble'
export { NexusNavigation, type NexusNavigationProps, type NexusNavigationItem } from './NexusNavigation'
export { NexusTypingIndicator, type NexusTypingIndicatorProps } from './NexusTypingIndicator'
export { NexusBadge, type NexusBadgeProps } from './NexusBadge'
export { NexusAvatar, NexusAvatarImage, NexusAvatarFallback } from './NexusAvatar'

// Enhanced Nexus Components
export { NexusLabel, type NexusLabelProps } from './NexusLabel'
export { NexusTextarea, type NexusTextareaProps } from './NexusTextarea'
export { NexusSkeleton, type NexusSkeletonProps } from './NexusSkeleton'
export { NexusSeparator, type NexusSeparatorProps } from './NexusSeparator'
export { NexusAlert, NexusAlertTitle, NexusAlertDescription, type NexusAlertProps } from './NexusAlert'
export { NexusSwitch, type NexusSwitchProps } from './NexusSwitch'
export { NexusCheckbox, type NexusCheckboxProps } from './NexusCheckbox'
export { NexusForm, type NexusFormProps } from './NexusForm'

// Re-exported UI Components (with original functionality)
export { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './accordion'
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from './alert-dialog'
export { Calendar } from './calendar'
export { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from './carousel'
export { ChartContainer, ChartTooltip, ChartTooltipContent, ChartLegend, ChartLegendContent, ChartStyle } from './chart'
export { Collapsible, CollapsibleContent, CollapsibleTrigger } from './collapsible'
export { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger, DialogClose, DialogOverlay, DialogPortal } from './dialog'
export { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuGroup, DropdownMenuPortal, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuRadioGroup } from './dropdown-menu'
export { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from './form'
export { Menubar, MenubarContent, MenubarItem, MenubarMenu, MenubarSeparator, MenubarShortcut, MenubarTrigger } from './menubar'
export { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, navigationMenuTriggerStyle } from './navigation-menu'
export { Popover, PopoverContent, PopoverTrigger } from './popover'
export { Progress } from './progress'
export { RadioGroup, RadioGroupItem } from './radio-group'
export { ScrollArea, ScrollBar } from './scroll-area'
export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './select'
export { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger, SheetClose } from './sheet'
export { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupAction, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInput, SidebarInset, SidebarMenu, SidebarMenuAction, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarMenuSkeleton, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarProvider, SidebarRail, SidebarSeparator, SidebarTrigger, useSidebar } from './sidebar'
export { Slider } from './slider'
export { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from './table'
export { Tabs, TabsContent, TabsList, TabsTrigger } from './tabs'
export { Toaster } from './toaster'
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './tooltip'
export { toast } from './use-toast'

// Export hooks
export { useNexusAnimations, type NexusAnimationConfig } from '@/hooks/useNexusAnimations'

// Legacy compatibility exports (use Nexus components instead)
export { NexusButton as Button } from './NexusButton'
export { NexusCard as Card } from './NexusCard'
export { NexusInput as Input } from './NexusInput'
export { NexusBadge as Badge } from './NexusBadge'
export { NexusAvatar as Avatar, NexusAvatarImage as AvatarImage, NexusAvatarFallback as AvatarFallback } from './NexusAvatar'
export { NexusLabel as Label } from './NexusLabel'
export { NexusTextarea as Textarea } from './NexusTextarea'
export { NexusSkeleton as Skeleton } from './NexusSkeleton'
export { NexusSeparator as Separator } from './NexusSeparator'
export { NexusAlert as Alert, NexusAlertTitle as AlertTitle, NexusAlertDescription as AlertDescription } from './NexusAlert'
export { NexusSwitch as Switch } from './NexusSwitch'
export { NexusCheckbox as Checkbox } from './NexusCheckbox'